### ISSUE TITLE
Incompatible to base >= 4.7

### ISSUE THREAD

**Issue by sheyll** [tel/inserts#3]
Hi, greate little project!

I'd like to use your project but it needs base in an incompatible version.

**Comment by tel** [comment]
Glad to hear. I am far from a functioning computer at the moment, but if you write a PR I can accept it quickly once that changes. If not, I'll review this in a few days.

—

**Comment by tel** [comment]
The most modern version of `inserts` now is 0.1.2 which works in base-4.7.
